export default [
    {
        id:1,
        name:'不知火舞',
        position:'法师',
        hero:'不知火舞',
        price:79,
        sex:'女',
        
        imgUrl:require('./lib/images/}K2UHZI2}ZN8SI%LDJLH5BQ.png') ,
        sales:998
    },
    {
        id:2,
        name:'貂蝉',
        position:'法师',
        hero:'貂蝉',
        price:71,
        sex:'女',
        imgUrl:require('./lib/images/C{]Z)M57$U(M4M{`(AYK$ZU.png'),
        sales:466
    },
    {
        id:3,
        name:'孙尚香',
        position:'ADC',
        hero:'孙尚香',
        price:55,
        sex:'女',
        imgUrl:require('./lib/images/~B_}~DF}%S@~FG`]OC(U(0D.png'),
        sales:884
    },
    {
        id:4,
        name:'兰陵王',
        position:'战士',
        hero:'兰陵王',
        price:74,
        sex:'男',
        imgUrl:require('./lib/images/1FT1~2_EL2I_S3}RL}MR[)R.png'),
        sales:642
    },
    {
        id:5,
        name:'钟无艳',
        position:'辅助',
        hero:'钟无艳',
        price:49,
        sex:'女',
        imgUrl:require('./lib/images/Q$C}@D)`G[)LYM){U2GT9@V.png'),
        sales:5999
    },
    {
        id:6,
        name:'曹操',
        position:'辅助',
        hero:'曹操',
        price:66,
        sex:'男',
        imgUrl:require('./lib/images/HGYGZ)$T]6H_S92PUG3%TDS.png'),
        sales:467
    },
    {
        id:7,
        name:'鲁班七号',
        position:'ADC',
        hero:'鲁班七号',
        price:53,
        sex:'男',
        imgUrl:require('./lib/images/LD}{01KPSAM1AAGWL}CT{~U.png'),
        sales:7992
    },
    {
        id:8,
        name:'伽罗',
        position:'ADC',
        hero:'伽罗',
        price:25,
        sex:'女',
        imgUrl:require('./lib/images/)IK[%QHVUHV({0$A3}[T3S2.png'),
        sales:953
    },
    {
        id:9,
        name:'司马懿',
        position:'法师',
        hero:'司马懿',
        price:41,
        sex:'男',
        imgUrl:require('./lib/images/DU4G8GJGFQI_M@ARUJRCC}S.png'),
        sales:932
    },
    {
        id:10,
        name:'孙策',
        position:'战士',
        hero:'孙策',
        price:180,
        sex:'男',
        imgUrl:require('./lib/images/`VD04~F@$@JTZU6HGKRXCUQ.png'),
        sales:9542
    },
    {
        id:11,
        name:'米莱迪',
        position:'法师',
        hero:'米莱迪',
        price:1000,
        sex:'男',
        imgUrl:require('./lib/images/7X_4_UC316WX)J2@9NW{U49.png'),
        sales:8502
    },
    {
        id:12,
        name:'杨玉环',
        position:'辅助',
        hero:'杨玉环',
        price:179,
        sex:'女',
        imgUrl:require('./lib/images/S$0ODVO_K8J}2D9Q_O(1MGN.png'),
        sales:832
    },
    {
        id:13,
        name:'明世隐',
        position:'辅助',
        hero:'明世隐',
        price:89,
        sex:'男',
        imgUrl:require('./lib/images/A(`WJ$)IK91$OLD]%}3ME_M.png'),
        sales:621
    },
    {
        id:14,
        name:'女娲',
        position:'法师',
        hero:'女娲',
        price:819,
        sex:'女',
        imgUrl:require('./lib/images/$_2R43L[)%}%QE82@GS54{2.png'),
        sales:6621
    },
    {
        id:15,
        name:'弈星',
        position:'法师',
        hero:'弈星',
        price:139,
        sex:'男',
        imgUrl:require('./lib/images/~{7BDKAP3_[O%P41CQG@}R5.png'),
        sales:221
    },
    {
        id:16,
        name:'元歌',
        position:'战士',
        hero:'元歌',
        price:59,
        sex:'男',
        imgUrl:require('./lib/images/BI99U(U`T4ZXKI)M02TA8R4.png'),
        sales:6321
    },
    {
        id:17,
        name:'梦琪',
        position:'战士',
        hero:'梦琪',
        price:59,
        sex:'女',
        imgUrl:require('./lib/images/08Q[Y~{YJH~1C]J_XDNFK7I.png'),
        sales:621
    },
    {
        id:18,
        name:'苏烈',
        position:'战士',
        hero:'苏烈',
        price:234,
        sex:'男',
        imgUrl:require('./lib/images/OP473}F~3L{(3]Y%)3EXQS4.png'),
        sales:6221
    },
    {
        id:19,
        name:'百里守约',
        position:'ADC',
        hero:'百里守约',
        price:99,
        sex:'男',
        imgUrl:require('./lib/images/_P)R`A}AX(O@74JJ3}XRU9N.png'),
        sales:3321
    },
    {
        id:20,
        name:'公孙离',
        position:'ADC',
        hero:'公孙离',
        price:81,
        sex:'女',
        imgUrl:require('./lib/images/P1RRA6K4B1NX9)5RU26OY]5.png'),
        sales:1221
    }
    
]